export const ROUTES = {
  LOGIN:               '/login',
  DASHBOARD:           '/dashboard',
  BROKERS:             '/brokers',
  BROKER_APPLICATIONS: '/brokers/applications',
  BROKER_DETAIL:       '/brokers/:id',
  CUSTOMERS:           '/customers',
  CUSTOMER_DETAIL:     '/customers/:id',
  PROPERTIES:          '/properties',
  PROPERTY_LISTINGS:   '/properties/listings',
  PROPERTY_DETAIL:     '/properties/:id',
  LEADS:               '/leads',
  PLANS:               '/plans',
  REVENUE:             '/revenue',
  TRANSACTIONS:        '/revenue/transactions',
  ANALYTICS:           '/analytics',
  NOTIFICATIONS:       '/notifications',
  SUB_ADMIN:           '/sub-admin',
  PERMISSIONS:         '/sub-admin/:id/permissions',
  SETTINGS:            '/settings',
}